<h3 style="font-family: 'montserratlight', sans-serif;margin-left: 20px;">Termos de Uso</h3>
<div  class="card-block-info" style="text-align: justify">
    <p>Estes Termos de Uso regulam a utilização da plataforma de intermediação de vendas de produtos digitais, infoprodutos, cursos online etc, na PLATAFORMA OPTIUM.</p>
    <p>O USUÁRIO, seja ele o cliente que realiza a compra ou o produtor que tem seu produto promovido na plataforma, expressamente declara que tem conhecimento e concorda com os Termos de Uso da PLATAFORMA OPTIUM, inclusive com as Políticas de Privacidade.</p>
    <p>Todo o marketing realizado para a venda dos produtos contidos nessa plataforma será realizado com base nas informações passadas pelo produtor. Assim a OPTIUM fica livre de qualquer responsabilidade de cumprimento do que foi contratado entre as partes. Mesmo que a OPTIUM produza conteúdos para a divulgação dos produtos, estes sempre estarão de acordo com a promessa do produtor na entrega do produto. Todo e qualquer produtor que, após investigação interna ficar comprovado que o mesmo não cumpriu com a entrega do prometido em sua oferta poderá ser excluído da plataforma.</p>
    <p>O usuário que se sentir lesado na compra de algum produto deve tomar as medidas devidas contra o produtor e entrar em contato com a OPTIUM, através do e-mail suporte@optium.com.br para que possamos tomar as devidas providências.</p>
    <p>O produtor, que após as devidas investigações ficar comprovado que o mesmo agiu com dolo e definitivamente não cumpriu com o prometido em seu produto poderá ser excluído da plataforma.</p>
    <p><strong>PRESTADORA DE SERVIÇOS DE INTERMEDIAÇÃO DE VENDAS DE PRODUTOS DIGITAIS</strong><br><br>
        Os serviços de intermediação de vendas de produtos digitais realizados na PLATAFORMA OPTIUM são realizados pela OPTIUM TECNOLOGIA E SERVICOS LTDA empresa brasileira, sediada em Inhumas/GO, na Rua Elpidio Luiz Brandão, nº 370, Centro.</p>
    <p><strong>CONTEÚDOS PROIBIDOS</strong><br><br>
        É expressamente proibido o anúncio ou a comercialização por meio da PLATAFORMA OPTIUM dos seguintes CONTEÚDOS:<br></p>
    <ul>
        <li>produtos que façam alusão narcóticos, tóxicos e qualquer sorte de drogas ilegais;</li>
        <li>produtos subtraídos de terceiros, furtados ou roubados;</li>
        <li>produtos falsificados ou adulterados;</li>
        <li>ações de empresas negociadas em Bolsa de Valores;</li>
        <li>listas de correio ou bases de dados pessoais;</li>
        <li>produtos que violem a intimidade, a honra, a imagem, o nome ou qualquer outro direito de personalidade de terceiros;</li>
        <li>produtos relacionados à pedofilia, à prostituição ou similares, material pornográfico, contendo cenas de nudez ou atos sexuais, ou de algum modo obsceno ou contrário à moral e os bons costumes;</li>
        <li>produtos que façam apologia do hábito de fumar;</li>
        <li>produtos que promovam esquemas de pirâmide, marketing multinível, etc.;</li>
        <li>produtos que prometam sucesso em loterias ou jogos de azar;</li>
        <li>produtos que promovam a violência e/ou a discriminação baseada em questões de raça, sexo, religião, nacionalidade, orientação sexual ou de qualquer outro tipo;</li>
        <li>produtos que prometam cura de problemas de saúde sem respaldo de uma organização reconhecidamente especializada no tema;</li>
        <li>produtos que contenham músicas e vídeos em quaisquer formatos, quando os mesmos não estão expressamente autorizados pelo artista ou gravadora titular dos direitos autorais;</li>
        <li>produtos que violem direitos intelectuais de terceiros, tais como produtos que violem software, direitos autorais, patentes, marcas, modelos e desenhos industriais, especialmente produtos que contenham software para OEM, NFR, cópias e/ou arquivos de backup, licença, programas acadêmicos e/ou desenvolvidos para alguma entidade educacional, ou segredos industriais;</li>
        <li>produtos afetados por alguma restrição de qualquer espécie quanto ao seu uso, exploração ou transferência de domínio ou posse;</li>
        <li>quaisquer outros produtos cuja venda seja expressamente proibida pelas leis vigentes no local da transação.</li>
    </ul>

    <p>Sendo papel de todos os usuários, caso verifiquem a existência de algum desses itens proibidos, entrar em contato com a plataforma através do e-mail suporte@optium.com.br com o assunto “conteúdo proibido” para que possamos tomar as medidas cabíveis.</p>
    <p><strong>DIRETRIZES GERAIS AO USUÁRIO</strong><br><br>
        Sem prejuízo de outras regras previstas nestes Termos de Uso, o USUÁRIO se compromete a não:<br><br>
         <strong>(i)</strong> COPIAR, MODIFICAR, REPRODUZIR, DISTRIBUIR, FAZER DOWNLOAD, ARMAZENAR, TRANSMITIR, VENDER, REVENDER, FAZER ENGENHARIA REVERSA OU CRIAR PRODUTOS DERIVADOS DE QUALQUER CONTEÚDO DISPONÍVEL NA PLATAFORMA OPTIUM;<br>
        <strong>(ii)</strong> Violar ou tentar violar quaisquer medidas de segurança da PLATAFORMA OPTIUM, ou tirar proveito de qualquer inconsistência do sistema para obter vantagem para si próprio ou para terceiros, ou causar prejuízo à OPTIUM e/ou a terceiros.<br>
        <strong>(iii)</strong> Submeter à PLATAFORMA OPTIUM qualquer informação falsa, imprecisa ou incompleta;<br>
        <strong>(iv)</strong> Manipular preços de CONTEÚDO;<br>
        <strong>(v)</strong> Interferir nas transações realizadas entre outros USUÁRIOS;<br>
        <strong>(vi)</strong> Passar-se por outra pessoa ou organização;<br>
        <strong>(vii)</strong> Usar SPAM ou qualquer outra prática de divulgação ou captação de informação inapropriada, caluniosa ou ilegal para promover qualquer CONTEÚDO inserido na PLATAFORMA OPTIUM;<br>
        <strong>(viii)</strong> Comprar CONTEÚDO através de seu próprio link de AFILIADO e/ou usar link de AFILIADOS de seu próprio CONTEÚDO em sua página de vendas, substituir o link de AFILIADO constante de uma página de vendas, em benefício próprio ou de terceiros;<br>
        <strong>(ix)</strong> Agredir, caluniar, injuriar ou difamar outros USUÁRIOS e/ou terceiros;</p>
    <p><strong>DIREITOS AUTORAIS</strong></p>
    <p>As informações contidas na PLATAFORMA OPTIUM, bem como as marcas, nome empresarial, nome de domínio, programas, bancos de dados, redes e arquivos são titularidade da OPTIUM e estão protegidos pelas leis e tratados internacionais de propriedade intelectual, sendo absolutamente vedada a cópia, distribuição, uso ou publicação, total ou parcial, de qualquer material, parte do site e dos CONTEÚDOS nele ofertados sem prévia e expressa autorização.</p>
    <p>Os PRODUTORES ficam, desde já, cientes do risco de terceiros criarem CONTEÚDOS com a mesma “ideia” dos comercializados por meio da PLATAFORMA OPTIUM, considerando a grande visualização de acessos que a Internet proporciona. No entanto, declaram reconhecer que a OPTIUM não pode impedir que isso ocorra, nem tem responsabilidade sobre essa situação, que foge completamente de seu controle, tendo em vista que ideias não são protegidas pela legislação aplicável e que a configuração de plágio é algo muito subjetivo que pode precisar ser avaliado pelo Poder Judiciário.</p>
    <p><strong>MECANISMOS DE DENÚNCIAS E RESOLUÇÃO DE DISPUTAS</strong></p>
    <p>Considerando que a PLATAFORMA OPTIUM não é a criadora do CONTEÚDO produzido e publicado pelo PRODUTOR e que não há controle editorial prévio dos CONTEÚDOS, a OPTIUM, nos termos da legislação aplicável, não é responsável pelos CONTEÚDOS divulgados.</p>
    <p>Disputas a respeito da qualidade do CONTEÚDO e da avaliação do PRODUTOR</p>
    <p>A OPTIUM recomenda que toda transação seja realizada com cautela e bom senso.</p>
    <p>A OPTIUM, de tempos em tempos, postará alguns depoimentos, tanto escritos como em vídeos dos clientes relatando as suas experiências no uso da plataforma e na compra de produtos.</p>
    <p>Caso alguém entenda que algum CONTEÚDO viole seus direitos de personalidade, tais como, a honra, a imagem, a voz, o nome, a intimidade, poderá enviar uma reclamação para suporte@optium.com com o assunto violação.</p>
    <p>Disputas a respeito de violação a direitos de propriedade intelectual</p>
    <p>Caso alguém entenda que um CONTEÚDO inserido na PLATAFORMA OPTIUM viola seus direitos de propriedade industrial (marca, patente, desenhos industriais) ou seus direitos autorais, poderá notificar a OPTIUM, enviando um e-mail para suporte@optium.com indicando a URL em que o CONTEÚDO em questão se encontra, anexando a comprovação de ser o titular do direito violado ou seu representante legal, via documentos juridicamente adequados para comprovar sua titularidade sobre o CONTEÚDO.</p>
    <p>Ao iniciar o procedimento disputas a respeito de violação a direitos de propriedade intelectual, todos os envolvidos concordam automaticamente com os termos e condições expressos na Política de Notificações sobre Violações de Direitos Intelectuais da PLATAFORMA OPTIUM.</p>
    <p>Notificar a PLATAFORMA OPTIUM a respeito de uma violação de direitos é um assunto sério com consequências jurídicas. Em caso de dúvida sobre a infração, recomenda-se buscar orientação jurídica. Antes de enviar uma Notificação, o USUÁRIO deve sempre lembrar que existem exceções e limitações aos direitos de cada um. O envio de denúncias enganosas sobre infrações pode ser punível por lei.</p>
    <p>Disputas a respeito de divulgação, sem autorização de seus participantes, de imagens, vídeos ou outros materiais contendo cenas de nudez ou de atos sexuais de caráter privado</p>
    <p>Caso alguém tome conhecimento de que um CONTEÚDO inserido na PLATAFORMA OPTIUM contenha cenas de nudez ou de atos sexuais de caráter privado a seu respeito, poderá notificar a OPTIUM, enviando um e-mail para suporte@optium.com, indicando a URL em que o CONTEÚDO em questão se encontra, bem como anexando ao formulário a comprovação de ser o participante da cena ou seu representante legal.</p>
    <p>Uma vez enviado o e-mail para suporte@optium.com , a OPTIUM verificará os requisitos de validade da notificação, conforme indicado acima, e constatada a existência de cenas de nudez ou de atos sexuais de caráter privado, providenciará em até 10 dias a remoção do CONTEÚDO, dando ciência ao Notificante e informando ao PRODUTOR responsável a sanção a ele aplicável, que poderá ser até o cancelamento definitivo da divulgação de seus produtos, a critério exclusivo da OPTIUM.</p>
    <p><strong>RELAÇÃO ENTRE USUÁRIOS E A OPTIUM</strong></p>
    <p>Sem prejuízo do já previsto nestes Termos de Uso, a relação entre a OPTIUM e os USUÁRIOS se regerá pelo seguinte:<br><br>
        <strong>(i)</strong> A OPTIUM é responsável pela guarda dos dados de cadastro dos USUÁRIOS;<br>
        <strong>(ii)</strong> Os USUÁRIOS serão única e exclusivamente responsáveis por manter todos os dados e informações cadastrais devidamente atualizados, responsabilizando pela veracidade, legalidade e adequação de todos os documentos e informações inseridos no sistema durante o cadastramento na PLATAFORMA OPTIUM. Caso sejam identificadas inconsistências ou desatualização dos dados e informações cadastrais, a OPTIUM poderá proceder com a imediata suspensão da conta do USUÁRIO até que esta seja regularizada;<br>
        <strong>(iii)</strong> A OPTIUM irá trabalhar junto com o comprador para resolver quaisquer problemas originados pela venda;<br>
        <strong>(iv)</strong> A OPTIUM não se responsabiliza (i) por qualquer dano, prejuízo ou perda no equipamento do USUÁRIO causada por falhas no sistema, no servidor ou na internet decorrentes de condutas de terceiros; (ii) por danos decorrentes de ataques de vírus ao equipamento do USUÁRIO em decorrência do acesso, utilização ou navegação na PLATAFORMA OPTIUM ou como consequência da transferência de dados, arquivos, imagens, textos ou áudio.<br>
        <strong>(v)</strong> Os USUÁRIOS isentam a OPTIUM de responsabilidade por danos suportados em virtude de prejuízos resultantes de dificuldades técnicas ou falhas nos sistemas ou na internet.<br>
        <strong>(vi)</strong> A OPTIUM não se responsabilizará por erros na divulgação de CONTEÚDO com a utilização das ferramentas contidas na PLATAFORMA OPTIUM, que possam dificultar a venda de tal CONTEÚDO.<br>
        <strong>(vii)</strong> A OPTIUM não é responsável pela qualidade dos CONTEÚDOS, mas recomenda que os PRODUTORES prezem pela qualidade dos CONTEÚDOS oferecidos na PLATAFORMA OPTIUM.<br>
        <strong>(viii)</strong> A OPTIUM realizará de tempos em tempos atualização das avaliações feitas pelos clientes que adquiriram os produtos, afim de que os usuários da OPTIUM tenham acesso ao feedback dado por quem comprou e utilizou o produto.<br>
        <strong>(ix)</strong> CONTEÚDOS incluídos na PLATAFORMA OPTIUM apenas permanecerão disponibilizados para divulgação se estiverem de acordo com estes Termos de Uso. A OPTIUM reserva-se o direito de remover qualquer CONTEÚDO que não esteja de acordo suas normas e políticas.<br>
        <strong>(x)</strong> A OPTIUM não é responsável pelo efetivo cumprimento das obrigações assumidas pelos USUÁRIOS.<br>
        <strong>(xi)</strong> A OPTIUM não é responsável por eventuais contestações, chargebacks ou bloqueios de compra/pagamento de qualquer natureza por parte do COMPRADOR e poderá deduzir a qualquer tempo do saldo do USUÁRIO valores referentes a transações reembolsadas ou bloqueadas, ou transações contestadas (chargeback);<br>
        <strong>(xii)</strong> A OPTIUM NÃO SE RESPONSABILIZA PELO USO INDEVIDO DA PLATAFORMA POR TERCEIROS, sejam PRODUTORES OU COMPRADORES, seja a que título for, especialmente em caso de divulgação em outras plataformas de CONTEÚDOS previamente adquiridos;<br>
        <strong>(xiii)</strong> Os USUÁRIOS reconhecem que o site da OPTIUM pode conter links para outros sites da rede, o que não significa que esses sites sejam de propriedade ou operados pela OPTIUM.<br>
        <strong>(xiv)</strong> A OPTIUM não se responsabiliza pelos materiais, informações ou conteúdo publicados em sites de terceiros, tampouco pela disponibilidade destes sites, competindo ao USUÁRIO usar seu próprio discernimento, precaução e senso comum ao acessar sites de terceiros, devendo conferir as políticas de privacidade e os termos de uso aplicáveis.<br>
        <strong>(xv)</strong> Todas as informações fornecidas pelo USUÁRIO à OPTIUM são armazenadas e tratadas na forma indicada na Política de Privacidade.<br>
        <strong>(xvi)</strong> Considerando a proposta de uso da PLATAFORMA OPTIUM como uma ferramenta para promover e anunciar CONTEÚDO, os USUÁRIOS estão cientes e consentem que toda a informação relevante será fornecida para habilitar PRODUTORES e informar os COMPRADORES quanto aos conteúdos disponibilizados na plataforma.<br>
        <strong>(xvii)</strong> A OPTIUM tomará todas as medidas possíveis para manter a confidencialidade e a segurança das informações dos USUÁRIOS, mas não poderá ser considerada responsável por perdas ou danos derivados da violação de tais medidas por terceiros que usarem redes públicas ou a Internet com o propósito de subverter o sistema de segurança e/ou ter acesso a informações confidenciais de USUÁRIOS.<br></p>
    <p>Considerando que a OPTIUM não é responsável pelo conteúdo gerado pelos PRODUTORES  em sua PLATAFORMA, a paralisação da venda do produto será mantido, em regra, até que <strong>(i)</strong> constate-se que o ato ou conduta suspeita não caracterizou prática ilegal, com base em critérios e avaliação exclusiva da OPTIUM; <strong>(ii)</strong> as partes envolvidas formalizem adequadamente a resolução amigável da questão; ou <strong>(iii)</strong> por ordem judicial ou determinação de autoridades administrativas que contenha identificação clara e específica do conteúdo ou ato apontado como infringente, permitindo sua adequada identificação e adoção das medidas requeridas. Caso reste confirmado a natureza ilegal da conduta, o bloqueio preventivo será convertido em definitivo, sendo que os valores eventualmente existentes na conta apenas serão liberados a quem de direito e mediante ordem judicial.</p>
    <p>Ressalta-se que o bloqueio preventivo citado acima não caracteriza aplicação de penalidade aos USUÁRIOS, por se tratar de uma medida cautelar adotada com o único objetivo de buscar evitar a ocorrência de danos, prejuízos ou infrações à direitos dos USUÁRIOS e terceiros.</p>
    <p><strong>PENALIDADES</strong></p>
    <p>Qualquer conduta contrária ao previsto nestes Termos de Uso poderá ser punida:<br><br>
        <strong>(a)</strong> Com a remoção de determinado CONTEÚDO;<br>
        <strong>(b)</strong> Com a suspensão imediata da venda do produto na plataforma;<br></p>
    <p>Tanto a remoção como a suspensão do conteúdo serão realizados a critério exclusivo da OPTIUM, após investigação interna, sem prejuízo de serem tomadas as ações legais cabíveis seja, pela própria OPTIUM ou por terceiros.</p>
    <p>Nos casos da paralisação da promoção de determinado produto/produtos, todos os anúncios ativos e/ou ofertas realizadas serão automaticamente cancelados, não assistindo ao USUÁRIO, por essa razão, qualquer direito de indenização ou ressarcimento.</p>
    <p>A OPTIUM, os USUÁRIOS ou quaisquer terceiros prejudicados poderão tomar as ações legais cabíveis em decorrência dos delitos ou contravenções de que sejam vítimas, ou ainda buscar o ressarcimento pelos prejuízos civis por descumprimento dos Termos de Uso, sem que isso acarrete qualquer direito de indenização por parte da OPTIUM ao USUÁRIO acionado.</p>
    <p><strong>ISENÇÃO DE RESPONSABILIDADE DA PLATAFORMA</strong></p>
    <p>Nos casos em que um ou mais USUÁRIOS ou algum terceiro inicie qualquer tipo de disputa, reclamação ou ação legal contra outro ou outros USUÁRIOS, todos os USUÁRIOS envolvidos nas disputas, reclamações ou ações eximem de toda responsabilidade a OPTIUM e a seus diretores, gerentes, empregados, agentes, operários, representantes e procuradores, inclusive no que tange os custos e honorários incorridos pelos USUÁRIOS para promover as disputas, reclamações ou ações.</p>
    <p><strong>INDENIZAÇÃO</strong></p>
    <p>O USUÁRIO concorda em ressarcir a OPTIUM, seus empregados, sócios, empresas afiliadas ou subsidiárias quaisquer despesas incorridas com ações judiciais oriundas de ações ou omissões do USUÁRIO que violem os presentes Termos de Uso ou as Políticas da OPTIUM, incluindo honorários advocatícios.</p>
    <p><strong>RESCISÃO</strong></p>
    <p>A OPTIUM poderá encerrar, a seu exclusivo critério, quaisquer serviços oferecidos e remover quaisquer CONTEÚDOS nele publicados a qualquer momento, com ou sem justa causa ou notificação prévia, e por qualquer razão ou motivo.</p>
    <p><strong>ALCANCE DOS SERVIÇOS</strong></p>
    <p>Estes Termos não geram nenhum contrato de sociedade, de mandato, parceria, franquia ou relação de trabalho entre a OPTIUM e o USUÁRIO.</p>
    <p><strong>MODIFICAÇÕES NOS TERMOS DE USO</strong></p>
    <p>Quando houver alteração nos Termos de Uso e nas Políticas da OPTIUM, o USUÁRIO será comunicado através de e-mail ou de publicação em área de destaque na PLATAFORMA OPTIUM.</p>
    <p>Ressalta-se que o presente Termos de Uso constitui o acordo entre as partes a que se refere. Nesse sentido, este instrumento prevalece sobre todas as propostas, entendimentos anteriores e todos os acordos, orais e escritos, eventualmente existentes entre as partes. Assim, a OPTIUM reserva-se o direito de alterar os Termos de Uso a qualquer momento. Após a comunicação referente as alterações dos Termos de Uso, conforme procedimentos mencionados acima, caso o USUÁRIO de continuidade ao uso da PLATAFORMA OPTIUM significará e será considerada como seu consentimento e aceitação irrevogável e irretratável. Dessa forma, o USUÁRIO concorda que tem o encargo de rever periodicamente o site (incluir endereço do site) para se informar sobre quaisquer alterações.</p>
    <p><strong>LEI APLICÁVEL</strong></p>
    <p>Estes Termos de Uso apresentam as normas aplicáveis ao uso da PLATAFORMA OPTIUM  disponível no  domínio optium.com.br, sendo certo que a OPTIUM TECNOLOGIA E SERVICOS LTDA empresa brasileira, sediada em Inhumas/GO , na Rua Elpidio Luiz Brandão, nº 370 , Centro,  é a responsável pela promoção/publicidade de produtos e serviços de terceiros, razão pela qual serão aplicáveis as leis brasileiras no tocante a essas operações, sendo que qualquer ação judicial relativa à sua interpretação ou aplicação deverá ser processada e julgada pelo Poder Judiciário Brasileiro.</p>
    <p><strong>FORO</strong></p>
    <p>Para operações realizadas a partir da prestação de serviço realizada pala OPTIUM fica eleito o foro da Comarca de Inhumas/GO como o único competente para dirimir eventuais controvérsias referentes à interpretação e ao cumprimento destes Termos de Uso e Política de Privacidade, independentemente de outro, por mais privilegiado que seja.</p>
    <p><strong>DÚVIDAS</strong></p>
    <p>Caso tenha qualquer dúvida em relação ao presente documento, o USUÁRIO poderá entrar em contato através do suporte@optium.com.br, utilizando no título da mensagem a frase: “Termos de Uso”.</p>

</div>